import 'dotenv/config'
import pg from 'pg'

const { Pool } = pg
const DATABASE_URL = process.env.NEON_DB || process.env.NEON_DATABASE_URL

if (!DATABASE_URL) {
  console.error('Missing NEON_DB or NEON_DATABASE_URL in .env')
  process.exit(1)
}

const pool = new Pool({ connectionString: DATABASE_URL })

const seedData = [
  {
    name: 'Bangkok',
    location: 'Bangkok, Central Thailand',
    description: "Thailand's bustling capital where ancient temples sit beside neon-lit skyscrapers, and world-famous street food costs less than $2.",
    image_url: '/images/bangkok.jpg',
    rating: 4.5,
    category: 'city',
    price_range: '$$',
    address: 'Phra Nakhon, Bangkok 10200, Thailand',
    latitude: 13.7563,
    longitude: 100.5018,
    google_map_embed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d60223.17002304996!2d100.4925!3d13.7518!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x100a7fa99b9c4d41%3A0x5b1d3e0b0b000000!2sBangkok%2C%20Thailand!5e0!3m2!1sen!2sth!4v1700000000000',
    google_review_rating: 4.7,
    google_review_count: 1250000,
    opening_hours: { monday: 'Open 24h', tuesday: 'Open 24h', wednesday: 'Open 24h', thursday: 'Open 24h', friday: 'Open 24h', saturday: 'Open 24h', sunday: 'Open 24h' },
    why_visit: "A dazzling blend of golden temples, chaotic markets, and the world's best street food — all for under $5.",
    best_time_to_visit: 'November to February for cool weather. Visit temples early morning to beat crowds and heat.',
    nearby_attractions: 'Grand Palace, Chatuchak Market, Khao San Road, Chatuchak Weekend Market',
    travel_tips: 'Use the BTS Skytrain or MRT subway to avoid traffic. Get a Rabbit Card or MRT card for easy travel.',
    visit_duration: '3-5 days',
    transport_options: 'BTS Skytrain, MRT, tuk-tuks, ride-hailing apps (Grab)',
    is_trending: true,
    is_featured: true,
  },
  {
    name: 'The Grand Palace',
    location: 'Bangkok, Central Thailand',
    description: 'The opulent former royal residence, home to the Emerald Buddha and dozens of stunning temples.',
    image_url: '/images/watmahathat.jpg',
    rating: 4.6,
    category: 'attraction',
    price_range: '$$',
    address: 'Na Phra Lan Rd, Phra Nakhon, Bangkok 10200, Thailand',
    latitude: 13.7518,
    longitude: 100.4932,
    google_map_embed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3789.305363367436!2d100.4918!3d13.7518!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x100a7fa9dcb8b8a1%3A0x8a0a0a0a0a0a0a0a!2sGrand%20Palace!5e0!3m2!1sen!2sth!4v1700000000000',
    google_review_rating: 4.6,
    google_review_count: 890000,
    opening_hours: { monday: '08:30-15:30', tuesday: '08:30-15:30', wednesday: '08:30-15:30', thursday: '08:30-15:30', friday: '08:30-15:30', saturday: '08:30-15:30', sunday: '08:30-15:30' },
    why_visit: "Wander through Thailand's most sacred site — the glittering Emerald Buddha temple complex alone is worth the trip.",
    best_time_to_visit: 'Open daily except when royal ceremonies close it. Arrive at 8:30 AM for fewer crowds. Dress modestly: shoulders and knees must be covered.',
    nearby_attractions: 'Wat Pho (Reclining Buddha), Wat Arun (Temple of Dawn), Chinatown',
    travel_tips: 'Take the Chao Phraya Express Boat to Tha Chang pier. Avoid tuk-tuks offering "shortened" routes.',
    visit_duration: 'Half day (3-4 hours)',
    transport_options: 'Chao Phraya Express Boat, BTS to Saphan Taksin',
    is_trending: false,
    is_featured: true,
  },
  {
    name: 'Thip Samai',
    location: 'Bangkok, Central Thailand',
    description: "World-famous for what many call the best pad thai in Bangkok — fresh, tangy, and served with a perfect wok hei char.",
    image_url: '/images/rotipairam.jpg',
    rating: 4.4,
    category: 'street_food',
    price_range: '$',
    address: '369/14 Samsen Rd, Phra Nakhon, Bangkok 10200, Thailand',
    latitude: 13.7583,
    longitude: 100.4972,
    google_map_embed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3789.4!2d100.495!3d13.758!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x100a7fa9!2sThip%20Samai!5e0!3m2!1sen!2sth!4v1700000000000',
    google_review_rating: 4.4,
    google_review_count: 25000,
    opening_hours: { monday: '16:00-01:00', tuesday: '16:00-01:00', wednesday: '16:00-01:00', thursday: '16:00-01:00', friday: '16:00-23:59', saturday: '16:00-01:00', sunday: '16:00-01:00' },
    why_visit: 'The pad thai here defined Bangkok street food. The smoky wok aroma and the price under $2 make this a pilgrimage site for food lovers.',
    best_time_to_visit: 'Best visited after 6 PM when the grill fires up. Go at 9 PM or later — the queue is part of the experience.',
    nearby_attractions: 'Nearby Yaowarat (Chinatown) for more night bites',
    travel_tips: 'Walk from Khao San Road. Grab a motorcycle taxi if you\'re in a hurry.',
    visit_duration: '30-45 min',
    transport_options: 'Walking, motorcycle taxi',
    is_trending: true,
    is_featured: true,
    must_try_dishes: 'Pad Thai (order level 2 spice for authentic heat), Mango Sticky Rice for dessert',
  },
  {
    name: 'Chiang Mai',
    location: 'Chiang Mai, Northern Thailand',
    description: "Northern Thailand's cultural heart, ringed by mountains and home to over 300 temples.",
    image_url: '/images/chiangmai.jpg',
    rating: 4.8,
    category: 'city',
    price_range: '$$',
    address: 'Mueang Chiang Mai, Chiang Mai 50200, Thailand',
    latitude: 18.7883,
    longitude: 98.9810,
    google_map_embed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d37685.0!2d98.981!3d18.788!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1sChiang%20Mai!5e0!3m2!1sen!2sth!4v1700000000000',
    google_review_rating: 4.7,
    google_review_count: 98000,
    opening_hours: { monday: 'Open 24h', tuesday: 'Open 24h', wednesday: 'Open 24h', thursday: 'Open 24h', friday: 'Open 24h', saturday: 'Open 24h', sunday: 'Open 24h' },
    why_visit: "Cool mountain air, ancient temples, and a food scene that's the soul of Northern Thailand — all wrapped in a relaxed old-city charm.",
    best_time_to_visit: 'November to February (cool season). Avoid the burning season (March-May) when air quality drops.',
    nearby_attractions: 'Doi Suthep, Old City Temples, Night Bazaar, Warorot Market',
    travel_tips: 'Rent a bicycle or tuk-tok to explore the Old City. Songthaew (shared red trucks) are cheap for getting around.',
    visit_duration: '3-4 days',
    transport_options: 'Songthaew, tuk-tok, bicycle rental, Grab',
    is_trending: true,
    is_featured: true,
  },
  {
    name: 'Wat Phra That Doi Suthep',
    location: 'Chiang Mai, Northern Thailand',
    description: 'Sacred mountaintop temple with golden stupa and panoramic views over Chiang Mai.',
    image_url: '/images/doisuthep.jpg',
    rating: 4.5,
    category: 'temple',
    price_range: '$',
    address: 'Doi Suthep, Mueang Chiang Mai, Chiang Mai 50200, Thailand',
    latitude: 18.8019,
    longitude: 98.9247,
    google_map_embed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d37685.0!2d98.925!3d18.802!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1sDoi%20Suthep!5e0!3m2!1sen!2sth!4v1700000000000',
    google_review_rating: 4.5,
    google_review_count: 52000,
    opening_hours: { monday: '06:00-18:00', tuesday: '06:00-18:00', wednesday: '06:00-18:00', thursday: '06:00-18:00', friday: '06:00-18:00', saturday: '06:00-18:00', sunday: '06:00-18:00' },
    why_visit: 'Climb (or take the funicular) to this golden mountaintop temple for sweeping views and a deeply spiritual atmosphere.',
    best_time_to_visit: 'Visit at sunrise for the most magical light. Wear long pants — dress code is strict.',
    nearby_attractions: 'Buppha Wat Boreham Marketplace, Chiang Mai Zoo, Nimman Road cafes',
    travel_tips: 'Take a songthaew or red truck up the mountain. Allow time for the climb or funicular queue.',
    visit_duration: 'Half day (2-3 hours)',
    transport_options: 'Songthaew, funicular, taxi',
    is_trending: false,
    is_featured: true,
  },
  {
    name: 'Khao Soi Khun Yai',
    location: 'Chiang Mai, Northern Thailand',
    description: "No-frills shack serving the iconic Chiang Mai-style khao soi — rich coconut curry noodle soup with crispy and soft egg noodles.",
    image_url: '/images/khaosoi.jpg',
    rating: 4.3,
    category: 'street_food',
    price_range: '$',
    address: '101/1-2 Soi 5, Sri Poom Rd, Tambon Sri Poom, Amphoe Mueang, Chiang Mai 50200, Thailand',
    latitude: 18.7815,
    longitude: 98.9606,
    google_map_embed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d37685.0!2d98.960!3d18.782!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1sKhao%20Soi%20Khun%20Yai!5e0!3m2!1sen!2sth!4v1700000000000',
    google_review_rating: 4.3,
    google_review_count: 18000,
    opening_hours: { monday: '08:00-18:00', tuesday: '08:00-18:00', wednesday: 'Closed', thursday: '08:00-18:00', friday: '08:00-18:00', saturday: '08:00-18:00', sunday: '08:00-18:00' },
    why_visit: 'This is where locals come for khao soi — a bowl of rich coconut curry broth, soft egg noodles, crispy shallots, and pickled mustard greens. It\'s the definitive Northern Thai comfort food.',
    best_time_to_visit: 'Open Tuesday-Sunday only. Arrive before 1 PM or go late afternoon to avoid the lunch rush. Ask for \'ped thai\' (extra crispy noodles) on top.',
    nearby_attractions: 'Warorot Market, Chiang Mai Gate, Nimmanhaemin Road',
    travel_tips: 'Located in the old city near Tha Phae Gate. Walkable from most Old City guesthouses.',
    visit_duration: '45-60 min',
    transport_options: 'Walking',
    is_trending: true,
    is_featured: true,
    must_try_dishes: 'Khao Soi (coconut curry noodle soup), Nam Prik Ong (spicy minced pork dip with vegetables)',
  },
  {
    name: 'Tong Tem Toh',
    location: 'Chiang Mai, Northern Thailand',
    description: 'Upscale Northern Thai restaurant serving authentic dishes like gaeng hang lay (spicy pork belly curry) and sai oua (herbal sausage).',
    image_url: '/images/khaosoi.jpg',
    rating: 4.4,
    category: 'restaurant',
    price_range: '$$',
    address: '51 Samlarn Rd, Tambon Phra Sing, Mueang Chiang Mai, Chiang Mai 50200, Thailand',
    latitude: 18.7825,
    longitude: 98.9686,
    google_map_embed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d37685.0!2d98.969!3d18.783!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1sTong%20Tem%20Toh!5e0!3m2!1sen!2sth!4v1700000000000',
    google_review_rating: 4.4,
    google_review_count: 3200,
    opening_hours: { monday: '11:00-22:00', tuesday: '11:00-22:00', wednesday: '11:00-22:00', thursday: '11:00-22:00', friday: '11:00-23:00', saturday: '11:00-23:00', sunday: '11:00-22:00' },
    why_visit: 'Authentic Northern Thai cuisine in a beautiful teak house setting. Try the gaeng hang lay and fresh herbs salad — these are the dishes Thais actually eat.',
    best_time_to_visit: 'Dinner is best here. Reservations recommended on weekends. Try their signature sai oua (herbal sausage).',
    nearby_attractions: 'Nimmanhaemin Road, Wat Phra That Doi Suthep, Chiang Mai Night Bazaar',
    travel_tips: 'In the old city near the Three Kings Monument. Easy walk from Tha Phae Road.',
    visit_duration: '1.5-2 hours',
    transport_options: 'Walking, tuk-tok',
    is_trending: false,
    is_featured: true,
    must_try_dishes: 'Gaeng Hang Lay (spicy pork belly curry), Sai Oua (Northern Thai herbal sausage), Nam Prik Num (green chili dip)',
  },
  {
    name: 'Phuket',
    location: 'Phuket, Southern Thailand',
    description: "Thailand's largest island with powder-white beaches, dramatic limestone cliffs, and a vibrant beach scene.",
    image_url: '/images/phuket.jpg',
    rating: 4.6,
    category: 'island',
    price_range: '$$$',
    address: 'Mueang Phuket, Phuket 83000, Thailand',
    latitude: 7.8804,
    longitude: 98.3067,
    google_map_embed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d37725.0!2d98.306!3d7.880!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1sPhuket!5e0!3m2!1sen!2sth!4v1700000000000',
    google_review_rating: 4.6,
    google_review_count: 75000,
    opening_hours: { monday: 'Open 24h', tuesday: 'Open 24h', wednesday: 'Open 24h', thursday: 'Open 24h', friday: 'Open 24h', saturday: 'Open 24h', sunday: 'Open 24h' },
    why_visit: 'Crystal-clear waters, dramatic cliffs at Railay, and beach clubs that stay open till sunrise.',
    best_time_to_visit: 'November to April (dry season). July-August is peak season for tourists.',
    nearby_attractions: 'Patong Beach, Big Buddha, Phi Phi Islands, Blue Tree',
    travel_tips: 'Rent a scooter for flexibility. Use Bolt/Grab for short trips. Avoid tuk-tuks on the island.',
    visit_duration: '4-5 days',
    transport_options: 'Scooter rental, tuk-tok, Bolt/Grab',
    is_trending: true,
    is_featured: true,
  },
  {
    name: 'Railay Beach',
    location: 'Krabi, Southern Thailand',
    description: 'Accessible only by boat, this limestone karst paradise offers world-class rock climbing and stunning beaches.',
    image_url: '/images/railay.jpg',
    rating: 4.7,
    category: 'beach',
    price_range: '$$',
    address: 'Railay, Mueang Krabi, Krabi 81000, Thailand',
    latitude: 7.9833,
    longitude: 99.4167,
    google_map_embed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d37760.0!2d99.416!3d7.983!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1sRailay%20Beach!5e0!3m2!1sen!2sth!4v1700000000000',
    google_review_rating: 4.6,
    google_review_count: 18000,
    opening_hours: { monday: 'Open 24h', tuesday: 'Open 24h', wednesday: 'Open 24h', thursday: 'Open 24h', friday: 'Open 24h', saturday: 'Open 24h', sunday: 'Open 24h' },
    why_visit: 'Towering limestone cliffs rising from emerald water — a UNESCO-recognized landscape that\'s a climber\'s and photographer\'s dream.',
    best_time_to_visit: 'Visit November to April for calm seas. Early morning or late afternoon for the best photos and fewer crowds.',
    nearby_attractions: 'Phra Nang Cave, Ao Nang, Tiger Cave Temple',
    travel_tips: 'Take a long-tail boat from Ao Nang or Krabi Town (15-30 min). No cars allowed on the beach.',
    visit_duration: 'Full day (6+ hours)',
    transport_options: 'Long-tail boat',
    is_trending: true,
    is_featured: true,
  },
  {
    name: 'Krua Thai Kaprao',
    location: 'Bangkok, Central Thailand',
    description: 'Humble shophouse serving authentic Thai home cooking — think stir-fried basil pork, green curry, and papaya salad.',
    image_url: '/images/rotipairam.jpg',
    rating: 4.2,
    category: 'restaurant',
    price_range: '$',
    address: '113/26 Maha Chai Rd, Tambon Wang Mahapu, Bang Rak, Bangkok 10500, Thailand',
    latitude: 13.7426,
    longitude: 100.5105,
    google_map_embed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3789.2!2d100.510!3d13.743!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1sKrua%20Thai!5e0!3m2!1sen!2sth!4v1700000000000',
    google_review_rating: 4.2,
    google_review_count: 4200,
    opening_hours: { monday: '10:30-21:00', tuesday: '10:30-21:00', wednesday: '10:30-21:00', thursday: '10:30-21:00', friday: '10:30-22:00', saturday: '10:30-22:00', sunday: '10:30-21:00' },
    why_visit: 'Where Bangkok locals eat after work — honest, flavorful Thai food without any tourist markup. The basil pork (krapow) is addictive.',
    best_time_to_visit: 'Come hungry and be ready to share tables. Cash only. Try the som tam (papaya salad) — it\'s properly spicy.',
    nearby_attractions: 'Chinatown (Yaowarat), Saphan Sung Market',
    travel_tips: 'In the historic Charoen Krung area, near Hua Lumphong.',
    visit_duration: '1-1.5 hours',
    transport_options: 'MRT, tuk-tok, walking',
    is_trending: false,
    is_featured: true,
    must_try_dishes: 'Pad Krapow Moo (basil pork with rice), Gaeng Som (sour curry), Som Tam (spicy papaya salad)',
  },
  {
    name: 'Mae Varee Mango Sticky Rice',
    location: 'Bangkok, Central Thailand',
    description: 'Famous for the best mango sticky rice in Bangkok — fresh mangoes, sweet coconut cream, and warm glutinous rice.',
    image_url: '/images/takahrai.jpg',
    rating: 4.3,
    category: 'cafe',
    price_range: '$',
    address: 'M Floor, Mango Tree Building, 384/14 Siam Rd, Ratchathewi, Bangkok 10400, Thailand',
    latitude: 13.7409,
    longitude: 100.5223,
    google_map_embed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3789.3!2d100.522!3d13.741!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1sMae%20Varee!5e0!3m2!1sen!2sth!4v1700000000000',
    google_review_rating: 4.3,
    google_review_count: 12000,
    opening_hours: { monday: '10:00-22:00', tuesday: '10:00-22:00', wednesday: '10:00-22:00', thursday: '10:00-22:00', friday: '10:00-23:00', saturday: '10:00-23:00', sunday: '10:00-22:00' },
    why_visit: 'The mango sticky rice here is legendary — sweet, fragrant, and perfectly balanced. It\'s the benchmark other places try to match.',
    best_time_to_visit: 'Best in season (March-August) when mangoes are at their peak. Expect a 15-minute queue — it\'s worth it.',
    nearby_attractions: 'Siam Paragon, MBK Center, Bangkok Art District',
    travel_tips: 'Inside Siam Discovery or near Siam BTS. Easy to combine with shopping.',
    visit_duration: '30 min',
    transport_options: 'BTS, walking',
    is_trending: false,
    is_featured: true,
    must_try_dishes: 'Mango Sticky Rice (Khao Niew Mamuang) — the seasonal version with fresh Nam Doc Mai mangoes',
  },
]

try {
  const count = await pool.query('SELECT COUNT(*) as cnt FROM destinations')
  if (count.rows[0].cnt === '0') {
    for (const d of seedData) {
      const cols = Object.keys(d)
      const vals = Object.values(d)
      const placeholders = vals.map((_, i) => `$${i + 1}`).join(', ')
      const colList = cols.join(', ')

      // Ensure must_try_dishes column exists
      await pool.query('ALTER TABLE destinations ADD COLUMN IF NOT EXISTS must_try_dishes TEXT')

      await pool.query(`INSERT INTO destinations (${colList}) VALUES (${placeholders})`, vals)
      console.log(`  Seeded: ${d.name}`)
    }
    console.log(`Seeded ${seedData.length} destinations`)
  } else {
    console.log(`Destinations already seeded (${count.rows[0].cnt} rows)`)
  }
} catch (err) {
  console.error('Seed error:', err.message)
} finally {
  await pool.end()
}
